version: 0.2

phases:
  pre_build:
    commands:
      - echo "Fetching AWS Account ID..."
      - export ACCOUNT_ID=$(aws sts get-caller-identity --query Account --output text)
      - export REGION=us-east-1
      - export REPOSITORY_URI=$ACCOUNT_ID.dkr.ecr.$REGION.amazonaws.com/sre-agent-runtime
      - echo "Logging in to Amazon ECR..."
      - aws ecr get-login-password --region $REGION | docker login --username AWS --password-stdin $ACCOUNT_ID.dkr.ecr.$REGION.amazonaws.com
      - echo "Repository URI:" $REPOSITORY_URI

  build:
    commands:
      - echo "Building ARM64 Docker image..."
      - docker build --platform linux/arm64 -t $REPOSITORY_URI:latest -f Dockerfile .
      - echo "Build completed on $(date)"

  post_build:
    commands:
      - echo "Pushing Docker image to ECR..."
      - docker push $REPOSITORY_URI:latest
      - echo "Image pushed successfully!"
      - echo "Image URI:" $REPOSITORY_URI:latest

cache:
  paths:
    - '/root/.cache/**/*'
